// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKybSg6CxjhE_mc5CwpMffwC3orI-tHkg',
    appId: '1:66873613449:android:c7d7c8b9b5bfc9db247a58',
    messagingSenderId: '66873613449',
    projectId: 'trendy-shop-fca78',
    storageBucket: 'trendy-shop-fca78.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe-e_gHWf6FRtydJeF-RAmWJfmUtCiVxI',
    appId: '1:66873613449:ios:d78d22b62415136a247a58',
    messagingSenderId: '66873613449',
    projectId: 'trendy-shop-fca78',
    storageBucket: 'trendy-shop-fca78.firebasestorage.app',
    iosBundleId: 'com.example.shopTrendy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe-e_gHWf6FRtydJeF-RAmWJfmUtCiVxI',
    appId: '1:66873613449:ios:d78d22b62415136a247a58',
    messagingSenderId: '66873613449',
    projectId: 'trendy-shop-fca78',
    storageBucket: 'trendy-shop-fca78.firebasestorage.app',
    iosBundleId: 'com.example.shopTrendy',
  );
}
